### ISSUE TITLE
改变文字或者图片图层时bug

### ISSUE THREAD

**Issue by chenyijie-bit** [Qiu-Jun/mobile-fabric-editor#2]
改变文字或者图片图层为最底层时，图片或文字就不能被再次选中了。

**Comment by Qiu-Jun** [comment]
> 改变文字或者图片图层为最底层时，图片或文字就不能被再次选中了。

收到，应该是工作层影响了

**Comment by Qiu-Jun** [comment]
> 改变文字或者图片图层为最底层时，图片或文字就不能被再次选中了。

你好，问题已处理，但是没更新到预览站点，你更新代码本地跑下看看
