### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by chenyijie-bit** [Qiu-Jun/mobile-fabric-editor#3]
![WechatIMG117](https://github.com/user-attachments/assets/4326b8d7-53b0-4be9-9f9a-d6bd33cb0028)
能否加一个这种可以展示图层的功能？

**Comment by Qiu-Jun** [comment]
图层展示，你可以参考我主页那个五千星的图片编辑器，简单做法就是每步存一次。如果需要基于这个定制的话也可以加个好友

**Comment by Qiu-Jun** [comment]
如果你想做的性能好一点，可以参考我首页yft design的思路。这个demo图层只是简单的处理。像你发的图案例，实现也是可以的，你可以看看我回复你的仓库的历史组件相关代码

**Comment by chenyijie-bit** [comment]
好的好的 感谢

**Comment by chenyijie-bit** [comment]
> 如果你想做的性能好一点，可以参考我首页yft design的思路。这个demo图层只是简单的处理。像你发的图案例，实现也是可以的，你可以看看我回复你的仓库的历史组件相关代码

test

**Comment by Qiu-Jun** [comment]
> 好的好的 感谢

这个仓库代码只是fabric基础的使用，一些基础场景，商用的话最好提炼一下
